### ISSUE TITLE
No such file or directory killall?

### ISSUE THREAD

**Issue by dennkaii** [anufrievroman/waypaper#8] opened 2023-09-24 04:03 UTC
`Error changing wallpaper: [Errno 2] No such file or directory: 'killall'`

this shows every time i try to change the wallpaper with SWW backend(haven't treid others)  currently on nixos and i got the package from the nixos unstable channel.

**Comment by anufrievroman** [comment] 2023-09-24 04:18
Hmm, interesting. But, `killall` command exists in NixOS, right?

Does the output also say something like this?
```
Selected image path: .somefile.jpg
Wallpaper was set with swww
```

Also, this error kills the program, or it just outputs into the terminal and nothing happens?

**Comment by anufrievroman** [comment] 2023-09-24 04:31
I pushed a quick fix to PyPi and to Github, so AUR and `pipx` versions should work. But I don't know who maintains the NixOS package, hopefully it will be updated soon too.

**Comment by dennkaii** [comment] 2023-09-24 13:05
> Also, this error kills the program, or it just outputs into the terminal and nothing happens?

Just output in the terminal

Already added the killall to global pkgs until someone fixes it

But know im getting 
![image](https://github.com/anufrievroman/waypaper/assets/70287696/1ba2a72c-7615-476d-8448-0767a5431a18)

even having the swww backend on the gui tho when i try via terminal it kinda works
![image](https://github.com/anufrievroman/waypaper/assets/70287696/ad810138-6607-477d-a146-10b022dc6766)

**Comment by anufrievroman** [comment] 2023-09-24 14:20
Some errors are normal to have, like "There seems to already be...", but your first screenshot is puzzling. I'll try to reproduce it tomorrow, but I think it is related to your first bug report and is likely already fixed with version 1.9.2. 

As a quick fix you can try to also install `swaybg` :D

Basically, what happens is that normally, before using `swww` program tries to kill `swaybg` because they don't play nicely together. My mistake was that I didn't put into try-except as I didn't imagine there could be a case when this can fail. Anyway, thank you for reporting!

**Comment by dennkaii** [comment] 2023-09-25 12:51
> As a quick fix you can try to also install `swaybg` :D

will try it, tysm for the response

**Comment by anufrievroman** [comment] 2023-10-09 13:15
I'll assume that this issue has been resolved

**Closed by anufrievroman** 2023-10-09 13:15 UTC
Labels: bug

**Comment by Gigas002** [comment] 2023-12-05 14:01
Is this behavior planned to be changed? While installing `swaybg` indeed fixes the issue, I personally don't want to install the tool I won't ever use

**Comment by anufrievroman** [comment] 2023-12-05 14:14
> @anufrievroman  Is this behavior planned to be changed? While installing `swaybg` indeed fixes the issue, I personally don't want to install the tool I won't ever use

Do you mean that you see the errors in the terminal? I mean, it is sort of normal behavior because it's GUI app, so I assumed the only time you'd see these errors is when you run it from the terminal for debugging, that's why it is quite generous with errors, but it's really an error, just information what it tried to do. So swaybg is not required at all. Or I don't understand the problem correctly?

**Comment by Gigas002** [comment] 2023-12-05 14:21
I try to run the application with `waypaper` command in the terminal. The app runs, but as soon as I try to change the background image, I get the above error `No such file or directory: swaybg`, and the bg image isn't changes. Only if I install the `swaybg` the error is gone and the background image changes.
